/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.Date;
import javax.swing.JOptionPane;
import model.dao.ClientNaturalDao;
import model.dao.DaoFactory;
import model.entities.ClientLegal;
import model.entities.ClientNatural;

/**
 *
 * @author Felipe Kellermann Wo
 */
public class PersonRegistration extends javax.swing.JFrame {

    /**
     * Creates new form PersonRegistration
     */
    public PersonRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Cadastro_de_pessoas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_salvar = new javax.swing.JButton();
        jButton_consultar = new javax.swing.JButton();
        jButton_alterar = new javax.swing.JButton();
        jButton_excluir = new javax.swing.JButton();
        jButton_limpar = new javax.swing.JButton();
        jLabel_codigo = new javax.swing.JLabel();
        jText_codigo = new javax.swing.JTextField();
        jLabel_data = new javax.swing.JLabel();
        jFormattedTextField_data = new javax.swing.JFormattedTextField();
        jLabel_pessoa = new javax.swing.JLabel();
        jCheckBox_pessoa_fisica = new javax.swing.JCheckBox();
        jCheckBox_pessoa_juridica = new javax.swing.JCheckBox();
        jLabel_sexo = new javax.swing.JLabel();
        jCheckBox_masculino = new javax.swing.JCheckBox();
        jCheckBox_feminino = new javax.swing.JCheckBox();
        jLabel_nome = new javax.swing.JLabel();
        jText_nome = new javax.swing.JTextField();
        jLabel_data_de_nasc = new javax.swing.JLabel();
        jFormattedTextField_data_nasc = new javax.swing.JFormattedTextField();
        jLabel_rg = new javax.swing.JLabel();
        jText_rg = new javax.swing.JTextField();
        jLabel_cpf = new javax.swing.JLabel();
        jFormattedTextField_cpf = new javax.swing.JFormattedTextField();
        jLabel_cnpj = new javax.swing.JLabel();
        jFormattedTextField_cnpj = new javax.swing.JFormattedTextField();
        jLabel_cnh = new javax.swing.JLabel();
        jText_cnh = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_tel_residencial = new javax.swing.JLabel();
        jFormattedTextField_tel_residencial = new javax.swing.JFormattedTextField();
        jLabel_celular = new javax.swing.JLabel();
        jFormattedTextField_celular = new javax.swing.JFormattedTextField();
        jFormattedTextField_whatsapp = new javax.swing.JFormattedTextField();
        jLabel_whatsapp = new javax.swing.JLabel();
        jText_email = new javax.swing.JTextField();
        jLabel_email = new javax.swing.JLabel();
        jLabel_cep = new javax.swing.JLabel();
        jFormattedTextField_cep = new javax.swing.JFormattedTextField();
        jLabel_n_predio_cond = new javax.swing.JLabel();
        jText_numero_predio_cond = new javax.swing.JTextField();
        jComboBox_uf_estado_federativo = new javax.swing.JComboBox<>();
        jLabel_estado = new javax.swing.JLabel();
        jLabel_pais = new javax.swing.JLabel();
        jText_pais = new javax.swing.JTextField();
        jText_bairro = new javax.swing.JTextField();
        jLabel_bairro = new javax.swing.JLabel();
        jLabel_rua = new javax.swing.JLabel();
        jText_rua = new javax.swing.JTextField();
        jText_numero_residencial = new javax.swing.JTextField();
        jLabel_n = new javax.swing.JLabel();
        jLabel_cidade = new javax.swing.JLabel();
        jText_cidade = new javax.swing.JTextField();
        jLabel_obs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_observacoes = new javax.swing.JTextArea();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setName("background"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1040, 684));
        setResizable(false);
        setSize(new java.awt.Dimension(1026, 684));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Cadastro_de_pessoas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel_Cadastro_de_pessoas.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Cadastro_de_pessoas.setText("C A D A S T R O    D E    C L I E N T E S");
        getContentPane().add(jLabel_Cadastro_de_pessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 815, 14));

        jButton_salvar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_salvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_salvar.setForeground(new java.awt.Color(204, 204, 204));
        jButton_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/save.png"))); // NOI18N
        jButton_salvar.setText("Salvar");
        jButton_salvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_salvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 130, -1));

        jButton_consultar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_consultar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_consultar.setForeground(new java.awt.Color(204, 204, 204));
        jButton_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        jButton_consultar.setText("Consultar");
        jButton_consultar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_consultar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 130, -1));

        jButton_alterar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_alterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_alterar.setForeground(new java.awt.Color(204, 204, 204));
        jButton_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
        jButton_alterar.setText("Alterar");
        jButton_alterar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_alterar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 130, -1));

        jButton_excluir.setBackground(new java.awt.Color(0, 0, 0));
        jButton_excluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_excluir.setForeground(new java.awt.Color(204, 204, 204));
        jButton_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete.png"))); // NOI18N
        jButton_excluir.setText("Excluir");
        jButton_excluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_excluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 130, -1));

        jButton_limpar.setBackground(new java.awt.Color(51, 51, 51));
        jButton_limpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_limpar.setForeground(new java.awt.Color(204, 204, 204));
        jButton_limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/clear.png"))); // NOI18N
        jButton_limpar.setText("Limpar");
        jButton_limpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_limpar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_limpar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limparActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 110, 40));

        jLabel_codigo.setText("Código:");
        getContentPane().add(jLabel_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        jText_codigo.setBackground(new java.awt.Color(102, 102, 102));
        jText_codigo.setForeground(new java.awt.Color(204, 204, 204));
        jText_codigo.setText("00001");
        jText_codigo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jText_codigo.setEnabled(false);
        jText_codigo.setMinimumSize(new java.awt.Dimension(6, 22));
        jText_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_codigoActionPerformed(evt);
            }
        });
        getContentPane().add(jText_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 111, 22));

        jLabel_data.setText("DATA:");
        getContentPane().add(jLabel_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, 20));

        try {
            jFormattedTextField_data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_data.setText("01122020");
        jFormattedTextField_data.setToolTipText("");
        jFormattedTextField_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_dataActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 90, 22));

        jLabel_pessoa.setText("Pessoa:");
        getContentPane().add(jLabel_pessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 50, 22));

        jCheckBox_pessoa_fisica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox_pessoa_fisica.setText("Fisica");
        jCheckBox_pessoa_fisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_pessoa_fisicaActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_pessoa_fisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, -1));

        jCheckBox_pessoa_juridica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox_pessoa_juridica.setText("Juridica");
        jCheckBox_pessoa_juridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_pessoa_juridicaActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_pessoa_juridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, 20));

        jLabel_sexo.setText("Sexo:");
        getContentPane().add(jLabel_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, 22));

        jCheckBox_masculino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_masculino.setText("Masc.");
        jCheckBox_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_masculinoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, 22));

        jCheckBox_feminino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_feminino.setText("Fem.");
        jCheckBox_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_femininoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_feminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, 22));

        jLabel_nome.setText("Nome:");
        getContentPane().add(jLabel_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 25));

        jText_nome.setText("João Silva da Silva da Silva da Silva");
        jText_nome.setMinimumSize(new java.awt.Dimension(6, 25));
        jText_nome.setPreferredSize(new java.awt.Dimension(6, 26));
        jText_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_nomeActionPerformed(evt);
            }
        });
        getContentPane().add(jText_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 563, 25));

        jLabel_data_de_nasc.setText("Data de Nasc.:");
        getContentPane().add(jLabel_data_de_nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, -1, 25));

        try {
            jFormattedTextField_data_nasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField_data_nasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 90, 25));

        jLabel_rg.setText("RG:");
        getContentPane().add(jLabel_rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 30, 25));

        jText_rg.setText("5009300100");
        jText_rg.setMinimumSize(new java.awt.Dimension(6, 22));
        jText_rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_rgActionPerformed(evt);
            }
        });
        getContentPane().add(jText_rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 113, 25));

        jLabel_cpf.setText("CPF:");
        jLabel_cpf.setRequestFocusEnabled(false);
        jLabel_cpf.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 30, 25));

        try {
            jFormattedTextField_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_cpfActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField_cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, 25));

        jLabel_cnpj.setText("CNPJ:");
        jLabel_cnpj.setRequestFocusEnabled(false);
        jLabel_cnpj.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel_cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, 25));

        try {
            jFormattedTextField_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_cnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_cnpjActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField_cnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 140, 25));

        jLabel_cnh.setText("CNH:");
        jLabel_cnh.setRequestFocusEnabled(false);
        jLabel_cnh.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel_cnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, 25));

        jText_cnh.setText("01005002070");
        jText_cnh.setMinimumSize(new java.awt.Dimension(6, 22));
        jText_cnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_cnhActionPerformed(evt);
            }
        });
        getContentPane().add(jText_cnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 113, 25));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 815, 14));

        jLabel_tel_residencial.setText("Telefone Fixo:");
        getContentPane().add(jLabel_tel_residencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 22));

        try {
            jFormattedTextField_tel_residencial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_tel_residencial.setText("51");
        jFormattedTextField_tel_residencial.setToolTipText("");
        getContentPane().add(jFormattedTextField_tel_residencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 120, 25));

        jLabel_celular.setText("Celular:");
        getContentPane().add(jLabel_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, 25));

        try {
            jFormattedTextField_celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_celular.setText("51");
        getContentPane().add(jFormattedTextField_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 120, 25));

        try {
            jFormattedTextField_whatsapp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_whatsapp.setText("51");
        getContentPane().add(jFormattedTextField_whatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 120, 25));

        jLabel_whatsapp.setText("WhatsApp:");
        getContentPane().add(jLabel_whatsapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, 22));

        jText_email.setText("fulanodasilva@hotmail.com");
        jText_email.setMinimumSize(new java.awt.Dimension(6, 25));
        jText_email.setPreferredSize(new java.awt.Dimension(6, 26));
        jText_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_emailActionPerformed(evt);
            }
        });
        getContentPane().add(jText_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 440, 25));

        jLabel_email.setText("E-mail:");
        getContentPane().add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 22));

        jLabel_cep.setText("CEP:");
        getContentPane().add(jLabel_cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 22));

        try {
            jFormattedTextField_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField_cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 120, 25));

        jLabel_n_predio_cond.setText("Nº Prédio / Cond:");
        getContentPane().add(jLabel_n_predio_cond, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, 22));

        jText_numero_predio_cond.setText("n/a");
        jText_numero_predio_cond.setMinimumSize(new java.awt.Dimension(6, 25));
        jText_numero_predio_cond.setPreferredSize(new java.awt.Dimension(6, 26));
        jText_numero_predio_cond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_numero_predio_condActionPerformed(evt);
            }
        });
        getContentPane().add(jText_numero_predio_cond, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 75, 25));

        jComboBox_uf_estado_federativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBox_uf_estado_federativo.setSelectedIndex(20);
        jComboBox_uf_estado_federativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_uf_estado_federativoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_uf_estado_federativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 50, 25));

        jLabel_estado.setText("UF:");
        getContentPane().add(jLabel_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, 25));

        jLabel_pais.setText("País:");
        getContentPane().add(jLabel_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, 22));

        jText_pais.setText("Brasil");
        jText_pais.setMinimumSize(new java.awt.Dimension(6, 25));
        jText_pais.setPreferredSize(new java.awt.Dimension(6, 26));
        jText_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_paisActionPerformed(evt);
            }
        });
        getContentPane().add(jText_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 120, 25));

        jText_bairro.setText("João Leal Leal");
        jText_bairro.setMinimumSize(new java.awt.Dimension(6, 25));
        jText_bairro.setPreferredSize(new java.awt.Dimension(6, 26));
        jText_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_bairroActionPerformed(evt);
            }
        });
        getContentPane().add(jText_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 290, 25));

        jLabel_bairro.setText("Bairro:");
        getContentPane().add(jLabel_bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, -1, 25));

        jLabel_rua.setText("Rua:");
        getContentPane().add(jLabel_rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, 22));

        jText_rua.setText("João Carlos da Silva Silva");
        jText_rua.setMinimumSize(new java.awt.Dimension(6, 25));
        jText_rua.setPreferredSize(new java.awt.Dimension(6, 26));
        jText_rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_ruaActionPerformed(evt);
            }
        });
        getContentPane().add(jText_rua, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 431, 25));

        jText_numero_residencial.setText("000000");
        jText_numero_residencial.setMinimumSize(new java.awt.Dimension(6, 25));
        jText_numero_residencial.setPreferredSize(new java.awt.Dimension(6, 26));
        jText_numero_residencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_numero_residencialActionPerformed(evt);
            }
        });
        getContentPane().add(jText_numero_residencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 97, 25));

        jLabel_n.setText("Nº:");
        getContentPane().add(jLabel_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, -1, 22));

        jLabel_cidade.setText("Cidade:");
        getContentPane().add(jLabel_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, -1, 22));

        jText_cidade.setText("João Leal Leal");
        jText_cidade.setMinimumSize(new java.awt.Dimension(6, 25));
        jText_cidade.setPreferredSize(new java.awt.Dimension(6, 26));
        jText_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_cidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jText_cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 220, 25));

        jLabel_obs.setText("Obs:");
        getContentPane().add(jLabel_obs, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, 22));

        jTextArea_observacoes.setColumns(20);
        jTextArea_observacoes.setRows(5);
        jTextArea_observacoes.setText("the gray fox jumped over the lazy dog");
        jScrollPane1.setViewportView(jTextArea_observacoes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 520, 70));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Background.jpg"))); // NOI18N
        background.setText("jLabel1");
        background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        background.setAlignmentY(0.0F);
        background.setFocusCycleRoot(true);
        background.setPreferredSize(new java.awt.Dimension(1030, 690));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1030, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salvarActionPerformed

        
        ClientNaturalDao clientNaturalDao = DaoFactory.createClientNaturalDao();

        ClientNatural cf = new ClientNatural();
        ClientLegal cj = new ClientLegal();

        cf.setDataCadastro(new Date());

        if (jCheckBox_pessoa_fisica.isSelected()) {

            if (jCheckBox_masculino.isSelected()) {
                cf.setSexo("Masculino");
            } else if (jCheckBox_feminino.isSelected()) {
                cf.setSexo("Feminino");
            } else {
                JOptionPane.showMessageDialog(this, "Escolha um dos sexos!", "Atencao", JOptionPane.WARNING_MESSAGE);

            }
            cf.setNome(jText_nome.getText());
            cf.setDataNascimento(jFormattedTextField_data_nasc.getText());
            cf.setRg(jText_rg.getText());
            cf.setCpf(jFormattedTextField_cpf.getText());
            cf.setCnh(jText_cnh.getText());
            cf.setTelefoneFixo(jFormattedTextField_tel_residencial.getText());
            cf.setCelular(jFormattedTextField_celular.getText());
            cf.setWhatsapp(jFormattedTextField_whatsapp.getText());
            cf.setEmail(jText_email.getText());
            cf.setCep(jFormattedTextField_cep.getText());
            cf.setRua(jText_rua.getText());
            cf.setNumeroResidencia(jText_numero_residencial.getText());
            cf.setNumeroPredioCond(jText_numero_predio_cond.getText());
            cf.setBairro(jText_bairro.getText());
            cf.setCidade(jText_cidade.getText());
            cf.setEstado((String) jComboBox_uf_estado_federativo.getSelectedItem());
            cf.setPais(jText_pais.getText());

            clientNaturalDao.insert(cf);

        } else if (jCheckBox_pessoa_juridica.isSelected()) {
            cj.setNome(jText_nome.getText());
            cj.setCnpj(jFormattedTextField_cnpj.getText());
            cj.setTelefoneFixo(jFormattedTextField_tel_residencial.getText());
            cj.setCelular(jFormattedTextField_celular.getText());
            cj.setWhatsapp(jFormattedTextField_whatsapp.getText());
            cj.setEmail(jText_email.getText());
            cj.setCep(jFormattedTextField_cep.getText());
            cj.setRua(jText_rua.getText());
            cj.setNumeroResidencia(jText_numero_residencial.getText());
            cj.setNumeroPredioCond(jText_numero_predio_cond.getText());
            cj.setBairro(jText_bairro.getText());
            cj.setCidade(jText_cidade.getText());
            cj.setEstado((String) jComboBox_uf_estado_federativo.getSelectedItem());
            cj.setPais(jText_pais.getText());

            //clientLegalDao.insert(cj);
        } else {
            JOptionPane.showMessageDialog(this, "Escolha o tipo de pessoa!", "Atencao", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_jButton_salvarActionPerformed

    private void jButton_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_consultarActionPerformed

    private void jButton_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_alterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_alterarActionPerformed

    private void jButton_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_excluirActionPerformed

    private void jButton_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limparActionPerformed

        //Botão Limpar:
        //Metodo limpar, limpa todos os campos preenchidos / reseta alguns campos para o dado mais usado!
        Limpar();
    }//GEN-LAST:event_jButton_limparActionPerformed

    private void jText_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_codigoActionPerformed

    private void jFormattedTextField_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_dataActionPerformed

    private void jCheckBox_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_masculinoActionPerformed
        // TODO add your handling code here:
        jCheckBox_feminino.setSelected(false);
    }//GEN-LAST:event_jCheckBox_masculinoActionPerformed

    private void jCheckBox_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_femininoActionPerformed
        // TODO add your handling code here:
        jCheckBox_masculino.setSelected(false);
    }//GEN-LAST:event_jCheckBox_femininoActionPerformed

    private void jText_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_nomeActionPerformed

    private void jText_rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_rgActionPerformed

    }//GEN-LAST:event_jText_rgActionPerformed

    private void jText_cnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_cnhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_cnhActionPerformed

    private void jText_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_emailActionPerformed

    private void jText_numero_predio_condActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_numero_predio_condActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_numero_predio_condActionPerformed

    private void jComboBox_uf_estado_federativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_uf_estado_federativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_uf_estado_federativoActionPerformed

    private void jText_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_paisActionPerformed

    private void jText_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_bairroActionPerformed

    private void jText_ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_ruaActionPerformed

    private void jText_numero_residencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_numero_residencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_numero_residencialActionPerformed

    private void jText_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_cidadeActionPerformed

    private void jFormattedTextField_cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_cnpjActionPerformed

    }//GEN-LAST:event_jFormattedTextField_cnpjActionPerformed

    private void jCheckBox_pessoa_fisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_pessoa_fisicaActionPerformed
        jCheckBox_pessoa_juridica.setSelected(false);
    }//GEN-LAST:event_jCheckBox_pessoa_fisicaActionPerformed

    private void jCheckBox_pessoa_juridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_pessoa_juridicaActionPerformed
        jCheckBox_pessoa_fisica.setSelected(false);
    }//GEN-LAST:event_jCheckBox_pessoa_juridicaActionPerformed

    private void jFormattedTextField_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_cpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonRegistration().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton_alterar;
    private javax.swing.JButton jButton_consultar;
    private javax.swing.JButton jButton_excluir;
    private javax.swing.JButton jButton_limpar;
    private javax.swing.JButton jButton_salvar;
    private javax.swing.JCheckBox jCheckBox_feminino;
    private javax.swing.JCheckBox jCheckBox_masculino;
    private javax.swing.JCheckBox jCheckBox_pessoa_fisica;
    private javax.swing.JCheckBox jCheckBox_pessoa_juridica;
    private javax.swing.JComboBox<String> jComboBox_uf_estado_federativo;
    private javax.swing.JFormattedTextField jFormattedTextField_celular;
    private javax.swing.JFormattedTextField jFormattedTextField_cep;
    private javax.swing.JFormattedTextField jFormattedTextField_cnpj;
    private javax.swing.JFormattedTextField jFormattedTextField_cpf;
    private javax.swing.JFormattedTextField jFormattedTextField_data;
    private javax.swing.JFormattedTextField jFormattedTextField_data_nasc;
    private javax.swing.JFormattedTextField jFormattedTextField_tel_residencial;
    private javax.swing.JFormattedTextField jFormattedTextField_whatsapp;
    private javax.swing.JLabel jLabel_Cadastro_de_pessoas;
    private javax.swing.JLabel jLabel_bairro;
    private javax.swing.JLabel jLabel_celular;
    private javax.swing.JLabel jLabel_cep;
    private javax.swing.JLabel jLabel_cidade;
    private javax.swing.JLabel jLabel_cnh;
    private javax.swing.JLabel jLabel_cnpj;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JLabel jLabel_data;
    private javax.swing.JLabel jLabel_data_de_nasc;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_estado;
    private javax.swing.JLabel jLabel_n;
    private javax.swing.JLabel jLabel_n_predio_cond;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_obs;
    private javax.swing.JLabel jLabel_pais;
    private javax.swing.JLabel jLabel_pessoa;
    private javax.swing.JLabel jLabel_rg;
    private javax.swing.JLabel jLabel_rua;
    private javax.swing.JLabel jLabel_sexo;
    private javax.swing.JLabel jLabel_tel_residencial;
    private javax.swing.JLabel jLabel_whatsapp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea_observacoes;
    private javax.swing.JTextField jText_bairro;
    private javax.swing.JTextField jText_cidade;
    private javax.swing.JTextField jText_cnh;
    private javax.swing.JTextField jText_codigo;
    private javax.swing.JTextField jText_email;
    private javax.swing.JTextField jText_nome;
    private javax.swing.JTextField jText_numero_predio_cond;
    private javax.swing.JTextField jText_numero_residencial;
    private javax.swing.JTextField jText_pais;
    private javax.swing.JTextField jText_rg;
    private javax.swing.JTextField jText_rua;
    // End of variables declaration//GEN-END:variables

    private void Limpar() {

        //Metodo Limpar: limpa todos os campos preenchidos / reseta alguns campos para o dado mais usado! 
        jFormattedTextField_data.setText("");
        jCheckBox_pessoa_fisica.setSelected(false);
        jCheckBox_pessoa_juridica.setSelected(false);
        jCheckBox_masculino.setSelected(false);
        jCheckBox_feminino.setSelected(false);
        jText_nome.setText("");
        jFormattedTextField_data_nasc.setText("");
        jText_rg.setText("");
        jFormattedTextField_cpf.setText("");
        jFormattedTextField_cnpj.setText("");
        jText_cnh.setText("");
        jFormattedTextField_tel_residencial.setText("(51) ");
        jFormattedTextField_celular.setText("(51) ");
        jText_email.setText("");
        jFormattedTextField_whatsapp.setText("(51) ");
        jFormattedTextField_cep.setText("");
        jText_rua.setText("");
        jText_numero_residencial.setText("");
        jText_numero_predio_cond.setText("");
        jText_bairro.setText("");
        jText_cidade.setText("");
        jComboBox_uf_estado_federativo.setSelectedItem(20);
        jText_pais.setText("Brasil");
        jTextArea_observacoes.setText("");

    }

}
